# -*- coding: utf-8 -*-
"""Optimized Classification Model with Feature Importance Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2teD6139c8LVt_2EbGOVdCfx1rgQrJZ
"""

Download Dataset: https://www.kaggle.com/datasets/imakash3011/online-shoppers-purchasing-intention-dataset

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
)

# Set global parameters for reproducibility and aesthetics
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
sns.set_theme(style="whitegrid")

# ==========================================
# 1. DATA SYNTHESIS & INGESTION (Simulating Kaggle Dataset)
# ==========================================
def generate_ecommerce_dataset(n_samples=2000):
    """Generates a structured synthetic e-commerce dataset."""
    ages = np.random.randint(18, 65, size=n_samples)
    genders = np.random.choice(["Male", "Female", "Other"], size=n_samples, p=[0.48, 0.48, 0.04])
    locations = np.random.choice(["North America", "Europe", "Asia", "South America"], size=n_samples)
    device_types = np.random.choice(["Mobile", "Desktop", "Tablet"], size=n_samples, p=[0.55, 0.35, 0.10])
    traffic_sources = np.random.choice(["Search Engine", "Social Media", "Email", "Direct", "Ads"], size=n_samples)

    pages_viewed = np.random.poisson(lam=6, size=n_samples) + 1
    time_on_site = np.round(pages_viewed * np.random.uniform(15, 45, size=n_samples), 2)
    cart_items = np.random.poisson(lam=1.2, size=n_samples)
    previous_purchases = np.random.poisson(lam=2.5, size=n_samples)
    discount_used = np.random.choice([0, 1], size=n_samples, p=[0.6, 0.4])
    days_since_last_visit = np.random.randint(1, 60, size=n_samples)

    # Latent propensity formula to model realistic purchase behaviors
    logit = (
        -2.5
        + 0.8 * cart_items
        + 0.01 * time_on_site
        + 0.25 * previous_purchases
        + 0.5 * discount_used
        - 0.02 * days_since_last_visit
        + np.random.normal(0, 0.5, size=n_samples)
    )
    prob = 1 / (1 + np.exp(-logit))
    purchase = (prob > 0.5).astype(int)

    df = pd.DataFrame({
        "CustomerID": [f"CUST_{i:05d}" for i in range(1, n_samples + 1)],
        "Age": ages,
        "Gender": genders,
        "Location": locations,
        "DeviceType": device_types,
        "TrafficSource": traffic_sources,
        "PagesViewed": pages_viewed,
        "TimeOnSite": time_on_site,
        "CartItems": cart_items,
        "PreviousPurchases": previous_purchases,
        "DiscountUsed": discount_used,
        "DaysSinceLastVisit": days_since_last_visit,
        "Purchase": purchase
    })

    # Introduce small amounts of missing values for pipeline testing
    df.loc[df.sample(frac=0.02, random_state=RANDOM_STATE).index, "Age"] = np.nan
    df.loc[df.sample(frac=0.02, random_state=RANDOM_STATE).index, "DeviceType"] = np.nan
    return df

df = generate_ecommerce_dataset()
print("--- Data Shape ---")
print(df.shape)
print("\n--- Target Distribution ---")
print(df["Purchase"].value_counts(normalize=True))

# ==========================================
# 2. EXPLORATORY DATA ANALYSIS & PREPARATION
# ==========================================
# Drop identifier column as instructed
df_clean = df.drop(columns=["CustomerID"])

X = df_clean.drop(columns=["Purchase"])
y = df_clean["Purchase"]

# Identify Feature Types
numerical_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()

print(f"\nNumerical Features ({len(numerical_cols)}): {numerical_cols}")
print(f"Categorical Features ({len(categorical_cols)}): {categorical_cols}")

# Train-Test Split (Stratified to maintain class distributions)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=RANDOM_STATE, stratify=y
)

# ==========================================
# 3. PREPROCESSING PIPELINE BUILD
# ==========================================
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore", drop="first"))
])

preprocessor = ColumnTransformer(transformers=[
    ("num", numeric_transformer, numerical_cols),
    ("cat", categorical_transformer, categorical_cols)
])

# ==========================================
# 4. BASELINE MODEL TRAINING & EVALUATION
# ==========================================
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=RANDOM_STATE),
    "Decision Tree": DecisionTreeClassifier(random_state=RANDOM_STATE),
    "Random Forest": RandomForestClassifier(random_state=RANDOM_STATE)
}

baseline_results = []

for name, model in models.items():
    pipe = Pipeline(steps=[("preprocessor", preprocessor), ("classifier", model)])
    pipe.fit(X_train, y_train)

    preds = pipe.predict(X_test)
    probs = pipe.predict_proba(X_test)[:, 1] if hasattr(pipe, "predict_proba") else None

    baseline_results.append({
        "Model": name,
        "Optimization Status": "Baseline",
        "Accuracy": accuracy_score(y_test, preds),
        "Precision": precision_score(y_test, preds),
        "Recall": recall_score(y_test, preds),
        "F1-Score": f1_score(y_test, preds),
        "ROC-AUC": roc_auc_score(y_test, probs) if probs is not None else np.nan
    })

baseline_df = pd.DataFrame(baseline_results)
print("\n--- Baseline Model Performance ---")
print(baseline_df.to_string(index=False))

# ==========================================
# 5. HYPERPARAMETER OPTIMIZATION (Random Forest)
# ==========================================
rf_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=RANDOM_STATE))
])

param_grid = {
    "classifier__n_estimators": [100, 200],
    "classifier__max_depth": [5, 10, 15, None],
    "classifier__min_samples_split": [2, 5],
    "classifier__min_samples_leaf": [1, 2],
    "classifier__class_weight": [None, "balanced"]
}

cv_strategy = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

grid_search = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=param_grid,
    scoring="f1",  # Primary metric chosen to balance Precision and Recall
    cv=cv_strategy,
    n_jobs=-1,
    verbose=0
)

grid_search.fit(X_train, y_train)

best_model = grid_search.best_estimator_
print(f"\nBest Hyperparameters: {grid_search.best_params_}")
print(f"Best CV F1-Score: {grid_search.best_score_:.4f}")

# Evaluate Optimized Model on Test Dataset
opt_preds = best_model.predict(X_test)
opt_probs = best_model.predict_proba(X_test)[:, 1]

opt_result = {
    "Model": "Random Forest",
    "Optimization Status": "Optimized",
    "Accuracy": accuracy_score(y_test, opt_preds),
    "Precision": precision_score(y_test, opt_preds),
    "Recall": recall_score(y_test, opt_preds),
    "F1-Score": f1_score(y_test, opt_preds),
    "ROC-AUC": roc_auc_score(y_test, opt_probs)
}

comparison_df = pd.concat([baseline_df, pd.DataFrame([opt_result])], ignore_index=True)
print("\n--- Model Comparison Summary ---")
print(comparison_df.to_string(index=False))

# ==========================================
# 6. FEATURE IMPORTANCE ANALYSIS
# ==========================================
# Extract feature names after One-Hot Encoding
cat_encoder = best_model.named_steps["preprocessor"].named_transformers_["cat"].named_steps["encoder"]
encoded_cat_cols = cat_encoder.get_feature_names_out(categorical_cols).tolist()
all_feature_names = numerical_cols + encoded_cat_cols

importances = best_model.named_steps["classifier"].feature_importances_

feature_imp_df = pd.DataFrame({
    "Feature": all_feature_names,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

print("\n--- Top 10 Most Influential Features ---")
print(feature_imp_df.head(10).to_string(index=False))

# Plot Feature Importances
plt.figure(figsize=(10, 6))
sns.barplot(x="Importance", y="Feature", data=feature_imp_df.head(10), palette="viridis")
plt.title("Top 10 Feature Importances (Optimized Random Forest)")
plt.xlabel("Gini Importance Score")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

# ==========================================
# 7. THRESHOLD ANALYSIS & CUSTOMER SEGMENTATION
# ==========================================
# Evaluate Custom Decision Threshold (0.40 to favor Recall)
custom_threshold = 0.40
custom_preds = (opt_probs >= custom_threshold).astype(int)

print(f"\n--- Metrics at Custom Threshold ({custom_threshold}) ---")
print(f"Precision: {precision_score(y_test, custom_preds):.4f}")
print(f"Recall:    {recall_score(y_test, custom_preds):.4f}")
print(f"F1-Score:  {f1_score(y_test, custom_preds):.4f}")

# Customer Risk Categorization
test_results = X_test.copy()
test_results["ActualPurchase"] = y_test.values
test_results["PurchaseProbability"] = opt_probs
test_results["Likelihood Category"] = pd.cut(
    test_results["PurchaseProbability"],
    bins=[0.0, 0.30, 0.60, 1.0],
    labels=["Low", "Medium", "High"],
    include_lowest=True
)

print("\n--- Customer Categorization Distribution ---")
print(test_results["Likelihood Category"].value_counts())

# ==========================================
# 8. SAVE FINAL MODEL PIPELINE
# ==========================================
joblib.dump(best_model, "purchase_prediction_model.pkl")
print("\nModel pipeline successfully saved as 'purchase_prediction_model.pkl'.")