# -*- coding: utf-8 -*-
"""apache_arrow_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WjYH-QIBzmrnIy-5oTj62KN4UsWTCDH7

## Apache Arrow Assignment Using Python

## Task 1: Create an Arrow Table
"""

import pyarrow as pa

data = {
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": ["Asha", "Rahul", "Neha", "Vikram", "Priya", "Arjun"],
    "department": ["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "salary": [60000, 45000, 70000, 55000, 48000, 65000],
    "city": ["Delhi", "Mumbai", "Bengaluru", "Delhi", "Mumbai", "Chennai"]
}

employee_table = pa.table(data)

print(employee_table)

"""## Task 2: Display the Schema"""

print(employee_table.schema)

"""## Task 3: Inspect the Table"""

print("Rows:", employee_table.num_rows)
print("Columns:", employee_table.num_columns)
print("Column names:", employee_table.column_names)

print(employee_table.column("name"))
print(employee_table.slice(0, 3))

"""## Task 4: Select Specific Columns"""

selected_table = employee_table.select(
    ["name", "department", "salary"]
)

print(selected_table)

"""## Task 5: Filter Records"""

import pyarrow.compute as pc

salary_filter = pc.greater(
    employee_table["salary"],
    50000
)

high_salary_table = employee_table.filter(salary_filter)

print(high_salary_table)

"""## Task 6: Filter by Department"""

department_filter = pc.equal(
    employee_table["department"],
    "IT"
)

it_employees = employee_table.filter(department_filter)

print(it_employees)

"""## Task 7: Perform Calculations"""

salary_column = employee_table["salary"]

print("Average salary:", pc.mean(salary_column).as_py())
print("Maximum salary:", pc.max(salary_column).as_py())
print("Minimum salary:", pc.min(salary_column).as_py())
print("Total salary:", pc.sum(salary_column).as_py())

"""## Task 8: Add a New Column"""

bonus_column = pc.multiply(
    employee_table["salary"],
    0.10
)

employee_table = employee_table.append_column(
    "bonus",
    bonus_column
)

print(employee_table)

"""## Task 9: Convert Arrow to Pandas"""

employee_df = employee_table.to_pandas()

print(employee_df)

"""## Task 10: Convert Pandas to Arrow"""

new_arrow_table = pa.Table.from_pandas(
    employee_df,
    preserve_index=False
)

print(new_arrow_table)

"""## Task 11: Save as a Parquet File"""

import pyarrow.parquet as pq

pq.write_table(
    employee_table,
    "employees.parquet"
)

print("Parquet file created successfully.")

"""## Task 12: Read the Parquet File"""

loaded_table = pq.read_table(
    "employees.parquet"
)

print(loaded_table)

"""## Task 13: Save as an Arrow IPC File"""

import pyarrow.ipc as ipc

with ipc.new_file(
    "employees.arrow",
    employee_table.schema
) as writer:
    writer.write_table(employee_table)

print("Arrow IPC file created successfully.")

"""## Task 14: Read the Arrow IPC File"""

with ipc.open_file("employees.arrow") as reader:
    ipc_table = reader.read_all()

print(ipc_table)

"""## Bonus Tasks

### Bonus Task 1: Display employees who work in Delhi.
"""

import pyarrow.compute as pc

delhi_employees_filter = pc.equal(
    employee_table["city"],
    "Delhi"
)

delhi_employees = employee_table.filter(delhi_employees_filter)

print(delhi_employees)

"""### Bonus Task 2: Display employees with salaries between `50000` and `65000`."""

salary_between_filter = pc.and_(
    pc.greater_equal(employee_table["salary"], 50000),
    pc.less_equal(employee_table["salary"], 65000)
)

salary_range_employees = employee_table.filter(salary_between_filter)

print(salary_range_employees)

"""### Bonus Task 3: Add a column named `annual_salary` by multiplying salary by `12`."""

annual_salary_column = pc.multiply(
    employee_table["salary"],
    12
)

employee_table = employee_table.append_column(
    "annual_salary",
    annual_salary_column
)

print(employee_table)

"""### Bonus Task 4: Save only IT employees to `it_employees.parquet`."""

import pyarrow.parquet as pq
import pyarrow.compute as pc

it_department_filter = pc.equal(
    employee_table["department"],
    "IT"
)

it_employees_table = employee_table.filter(it_department_filter)

pq.write_table(
    it_employees_table,
    "it_employees.parquet"
)

print("IT employees Parquet file created successfully.")

"""### Bonus Task 5: Read only the `name` and `salary` columns from the Parquet file."""

import pyarrow.parquet as pq

selected_columns = pq.read_table(
    "employees.parquet",
    columns=["name", "salary"]
)

print(selected_columns)

"""### Bonus Task 6: Sort employees by salary from highest to lowest."""

sorted_employees = employee_table.sort_by([('salary', 'descending')])

print(sorted_employees)