# -*- coding: utf-8 -*-
"""duckdb_parquet_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxXwaGaBnn6QAED_now3DEA4tSZVIe0q

## Setup: Install Libraries

## Task 1: Create the Parquet File"""

import pandas as pd

data = {
    "employee_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "name": [
        "Asha",
        "Rahul",
        "Neha",
        "Vikram",
        "Priya",
        "Arjun",
        "Meera",
        "Karan"
    ],
    "department": [
        "IT",
        "HR",
        "IT",
        "Finance",
        "HR",
        "Finance",
        "IT",
        "Sales"
    ],
    "salary": [
        60000,
        45000,
        70000,
        55000,
        48000,
        65000,
        75000,
        50000
    ],
    "city": [
        "Delhi",
        "Mumbai",
        "Bengaluru",
        "Delhi",
        "Mumbai",
        "Chennai",
        "Bengaluru",
        "Delhi"
    ]
}

df = pd.DataFrame(data)

df.to_parquet(
    "employees.parquet",
    index=False
)

print("Parquet file created successfully.")

"""## Task 2: Read Parquet Using DuckDB"""

import duckdb

result = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
""").df()

print(result)

"""## Task 3: Filter Employee Records

### 1. Employees with a salary greater than `50000`
"""

high_salary_employees = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    WHERE salary > 50000
""").df()

print(high_salary_employees)

"""### 2. Employees from the `IT` department"""

it_employees = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    WHERE department = 'IT'
""").df()

print(it_employees)

"""### 3. Employees who work in `Delhi`"""

delhi_employees = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    WHERE city = 'Delhi'
""").df()

print(delhi_employees)

"""### 4. Employees from the `IT` department with a salary greater than `65000`"""

it_high_salary_employees = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    WHERE department = 'IT' AND salary > 65000
""").df()

print(it_high_salary_employees)

"""## Task 4: Select Specific Columns"""

selected_columns_sorted = duckdb.sql("""
    SELECT name, department, salary
    FROM read_parquet('employees.parquet')
    ORDER BY salary DESC
""").df()

print(selected_columns_sorted)

"""## Task 5: Perform Aggregations"""

summary = duckdb.sql("""
    SELECT
        COUNT(*) AS employee_count,
        AVG(salary) AS average_salary,
        MAX(salary) AS maximum_salary,
        MIN(salary) AS minimum_salary,
        SUM(salary) AS total_salary
    FROM read_parquet('employees.parquet')
""").df()

print(summary)

"""## Task 6: Group Data"""

department_summary = duckdb.sql("""
    SELECT
        department,
        COUNT(*) AS employee_count,
        AVG(salary) AS average_salary,
        MAX(salary) AS highest_salary,
        SUM(salary) AS total_salary
    FROM read_parquet('employees.parquet')
    GROUP BY department
    ORDER BY average_salary DESC
""").df()

print(department_summary)

"""## Task 7: Create a DuckDB Table"""

import duckdb

connection = duckdb.connect("company.duckdb")

connection.execute("""
    CREATE OR REPLACE TABLE employees AS
    SELECT *
    FROM read_parquet('employees.parquet')
""")

result = connection.execute("""
    SELECT *
    FROM employees
""").df()

print(result)

connection.close()

"""## Task 8: Export Query Results to Parquet"""

import duckdb

duckdb.sql("""
    COPY (
        SELECT *
        FROM read_parquet('employees.parquet')
        WHERE salary > 50000
    )
    TO 'high_salary_employees.parquet'
    (FORMAT PARQUET)
""")

print("Filtered Parquet file created.")

"""## Task 9: Verify the Exported File"""

result = duckdb.sql("""
    SELECT *
    FROM read_parquet(
        'high_salary_employees.parquet'
    )
""").df()

print(result)

"""## Bonus Tasks

### 1. Find the employee with the second-highest salary.
"""

second_highest_salary_employee = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    ORDER BY salary DESC
    LIMIT 1 OFFSET 1
""").df()

print(second_highest_salary_employee)

"""### 2. Display the top three highest-paid employees."""

top_three_highest_paid_employees = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    ORDER BY salary DESC
    LIMIT 3
""").df()

print(top_three_highest_paid_employees)

"""### 3. Calculate the average salary for each city."""

avg_salary_by_city = duckdb.sql("""
    SELECT
        city,
        AVG(salary) AS average_salary
    FROM read_parquet('employees.parquet')
    GROUP BY city
    ORDER BY average_salary DESC
""").df()

print(avg_salary_by_city)

"""### 4. Find departments with an average salary greater than `55000`."""

departments_high_avg_salary = duckdb.sql("""
    SELECT
        department,
        AVG(salary) AS average_salary
    FROM read_parquet('employees.parquet')
    GROUP BY department
    HAVING AVG(salary) > 55000
    ORDER BY average_salary DESC
""").df()

print(departments_high_avg_salary)

"""### 5. Add a calculated column named `salary_category`"""

salary_category_employees = duckdb.sql("""
    SELECT
        name,
        salary,
        CASE
            WHEN salary >= 65000 THEN 'High'
            WHEN salary >= 50000 THEN 'Medium'
            ELSE 'Low'
        END AS salary_category
    FROM read_parquet('employees.parquet')
    ORDER BY salary DESC
""").df()

print(salary_category_employees)