from pathlib import Path

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

from src.data_loader import load_datasets, optimize_dataset


BASE_DIR = Path(__file__).resolve().parent.parent
RESULTS_DIR = BASE_DIR / "results"

PREDICTIONS_FILE = RESULTS_DIR / "ensemble_predictions.csv"


def load_ensemble_predictions():
    """Load predictions generated by the ensemble pipeline."""

    if not PREDICTIONS_FILE.exists():
        raise FileNotFoundError(
            f"Ensemble predictions not found:\n{PREDICTIONS_FILE}\n\n"
            "Run `python -m src.ensemble` first."
        )

    return pd.read_csv(PREDICTIONS_FILE)


def get_true_labels(test_ds):
    """Extract true labels from the test dataset."""

    labels = []

    for _, batch_labels in test_ds:
        labels.extend(batch_labels.numpy())

    return np.array(labels)


def evaluate_predictions(y_true, y_pred):
    """Calculate classification metrics."""

    accuracy = accuracy_score(y_true, y_pred)

    precision = precision_score(
        y_true,
        y_pred,
        zero_division=0,
    )

    recall = recall_score(
        y_true,
        y_pred,
        zero_division=0,
    )

    f1 = f1_score(
        y_true,
        y_pred,
        zero_division=0,
    )

    return accuracy, precision, recall, f1


def main():

    print("=" * 70)
    print("TASK 15 - ENSEMBLE MODEL EVALUATION")
    print("=" * 70)

    # ---------------------------------------------------------
    # Load test dataset
    # ---------------------------------------------------------

    print("\nLoading test dataset...")

    _, _, test_ds = load_datasets()

    test_ds = optimize_dataset(test_ds)

    print("Test dataset loaded.")
    print(f"Classes: {['def_front', 'ok_front']}")

    # ---------------------------------------------------------
    # Load ensemble predictions
    # ---------------------------------------------------------

    print("\nLoading ensemble predictions...")

    predictions_df = load_ensemble_predictions()

    print(f"Prediction file: {PREDICTIONS_FILE}")
    print(f"Prediction rows: {len(predictions_df)}")

    # ---------------------------------------------------------
    # Extract true labels
    # ---------------------------------------------------------

    y_true = get_true_labels(test_ds)

    print(f"True labels: {len(y_true)}")

    # ---------------------------------------------------------
    # Detect prediction column
    # ---------------------------------------------------------

    possible_prediction_columns = [
        "ensemble_prediction",
        "prediction",
        "predicted_label",
        "ensemble_pred",
    ]

    prediction_column = None

    for column in possible_prediction_columns:
        if column in predictions_df.columns:
            prediction_column = column
            break

    if prediction_column is None:
        raise ValueError(
            "Could not find ensemble prediction column.\n"
            f"Available columns: {list(predictions_df.columns)}"
        )

    y_pred = predictions_df[prediction_column].to_numpy()

    # ---------------------------------------------------------
    # Convert predictions to integer labels
    # ---------------------------------------------------------

    y_pred = np.asarray(y_pred)

    if y_pred.dtype.kind in {"f", "c"}:
        y_pred = (y_pred >= 0.5).astype(int)

    y_pred = y_pred.astype(int)

    # ---------------------------------------------------------
    # Safety check
    # ---------------------------------------------------------

    if len(y_true) != len(y_pred):

        raise ValueError(
            f"Number of true labels ({len(y_true)}) does not match "
            f"predictions ({len(y_pred)})."
        )

    # ---------------------------------------------------------
    # Calculate metrics
    # ---------------------------------------------------------

    accuracy, precision, recall, f1 = evaluate_predictions(
        y_true,
        y_pred,
    )

    # ---------------------------------------------------------
    # Display results
    # ---------------------------------------------------------

    print("\n" + "=" * 70)
    print("ENSEMBLE EVALUATION RESULTS")
    print("=" * 70)

    print(f"Accuracy : {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall   : {recall:.4f}")
    print(f"F1 Score : {f1:.4f}")

    # ---------------------------------------------------------
    # Confusion matrix
    # ---------------------------------------------------------

    cm = confusion_matrix(y_true, y_pred)

    print("\nConfusion Matrix:")
    print(cm)

    # ---------------------------------------------------------
    # Classification report
    # ---------------------------------------------------------

    print("\nClassification Report:")
    print(
        classification_report(
            y_true,
            y_pred,
            target_names=[
                "defective",
                "non-defective",
            ],
            zero_division=0,
        )
    )

    # ---------------------------------------------------------
    # Save evaluation results
    # ---------------------------------------------------------

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    evaluation_file = RESULTS_DIR / "evaluation_results.txt"

    with open(evaluation_file, "w", encoding="utf-8") as file:

        file.write("TASK 15 - ENSEMBLE MODEL EVALUATION\n")
        file.write("=" * 50 + "\n\n")

        file.write(f"Accuracy : {accuracy:.4f}\n")
        file.write(f"Precision: {precision:.4f}\n")
        file.write(f"Recall   : {recall:.4f}\n")
        file.write(f"F1 Score : {f1:.4f}\n\n")

        file.write("Confusion Matrix:\n")
        file.write(str(cm))
        file.write("\n\n")

        file.write("Classification Report:\n")
        file.write(
            classification_report(
                y_true,
                y_pred,
                target_names=[
                    "defective",
                    "non-defective",
                ],
                zero_division=0,
            )
        )

    print(f"Evaluation report saved to:")
    print(evaluation_file)

    print("\n" + "=" * 70)
    print("EVALUATION COMPLETE")
    print("=" * 70)


if __name__ == "__main__":
    main()