# -*- coding: utf-8 -*-
"""Apache- arrow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VySPPWjHcLIhExZardKdL3gHFpw15ola
"""

import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.parquet as pq
import pyarrow.ipc as ipc


# Create an Arrow Table

data = {
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": ["Asha", "Rahul", "Neha", "Vikram", "Priya", "Arjun"],
    "department": ["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "salary": [60000, 45000, 70000, 55000, 48000, 65000],
    "city": ["Delhi", "Mumbai", "Bengaluru", "Delhi", "Mumbai", "Chennai"]
}

employee_table = pa.table(data)

print("===  1: Arrow table ===")
print(employee_table)
print()


# Display the Schema

print("===  2: Schema ===")
print(employee_table.schema)
print()


# Inspect the Table
print("=== Table inspection ===")
print("Rows:", employee_table.num_rows)
print("Columns:", employee_table.num_columns)
print("Column names:", employee_table.column_names)
print()
print("Name column:")
print(employee_table.column("name"))
print()
print("First three rows:")
print(employee_table.slice(0, 3))
print()


# Select Specific Columns

selected_table = employee_table.select(
    ["name", "department", "salary"]
)

print("===  4: name, department, salary ===")
print(selected_table)
print()


# Filter Records (salary > 50000)

salary_filter = pc.greater(
    employee_table["salary"],
    50000
)

high_salary_table = employee_table.filter(salary_filter)

print("===  5: Employees with salary > 50000 ===")
print(high_salary_table)
print()


# Filter by Department (IT)

department_filter = pc.equal(
    employee_table["department"],
    "IT"
)

it_employees = employee_table.filter(department_filter)

print("===  6: IT department employees ===")
print(it_employees)
print()


# Perform Calculations

salary_column = employee_table["salary"]

print("===  7: Salary calculations ===")
print("Average salary:", pc.mean(salary_column).as_py())
print("Maximum salary:", pc.max(salary_column).as_py())
print("Minimum salary:", pc.min(salary_column).as_py())
print("Total salary:", pc.sum(salary_column).as_py())
print()


# Add a New Column (bonus = 10% of salary)

bonus_column = pc.multiply(
    employee_table["salary"],
    0.10
)

employee_table = employee_table.append_column(
    "bonus",
    bonus_column
)

print("===  8: Table with bonus column ===")
print(employee_table)
print()


# Convert Arrow to Pandas

employee_df = employee_table.to_pandas()

print("===  9: Converted to Pandas DataFrame ===")
print(employee_df)
print()


# Convert Pandas to Arrow
new_arrow_table = pa.Table.from_pandas(
    employee_df,
    preserve_index=False
)

print("===  10: Converted back to Arrow table ===")
print(new_arrow_table)
print()


# Save as a Parquet File
pq.write_table(
    employee_table,
    "employees.parquet"
)

print("Parquet file created successfully.")
print()


# Read the Parquet File
loaded_table = pq.read_table(
    "employees.parquet"
)

print("===  12: Loaded from employees.parquet ===")
print(loaded_table)
print()


# Save as an Arrow IPC File
with ipc.new_file(
    "employees.arrow",
    employee_table.schema
) as writer:
    writer.write_table(employee_table)

print("Arrow IPC file created successfully.")
print()


# Read the Arrow IPC File

with ipc.open_file("employees.arrow") as reader:
    ipc_table = reader.read_all()

print("===  14: Loaded from employees.arrow ===")
print(ipc_table)
print()


# Bonus tasks
# 1. Employees who work in Delhi
delhi_filter = pc.equal(employee_table["city"], "Delhi")
delhi_employees = employee_table.filter(delhi_filter)

print("=== Bonus 1: Employees in Delhi ===")
print(delhi_employees)
print()

# 2. Employees with salaries between 50000 and 65000
salary_range_filter = pc.and_(
    pc.greater_equal(employee_table["salary"], 50000),
    pc.less_equal(employee_table["salary"], 65000)
)
salary_range_employees = employee_table.filter(salary_range_filter)

print("=== Bonus 2: Employees with salary between 50000 and 65000 ===")
print(salary_range_employees)
print()

# 3. annual_salary column (salary * 12)
annual_salary_column = pc.multiply(employee_table["salary"], 12)
employee_table = employee_table.append_column(
    "annual_salary",
    annual_salary_column
)

print("=== Bonus 3: Table with annual_salary column ===")
print(employee_table)
print()

# 4. Saving only IT employees to it_employees.parquet
it_department_filter = pc.equal(employee_table["department"], "IT")
it_only_table = employee_table.filter(it_department_filter)

pq.write_table(it_only_table, "it_employees.parquet")

print("it_employees.parquet created successfully.")
print()

# 5. Read only name and salary columns from the Parquet file
selected_columns = pq.read_table(
    "employees.parquet",
    columns=["name", "salary"]
)

print("=== Bonus 5: name and salary columns only ===")
print(selected_columns)
print()

# 6. Sort employees by salary, highest to lowest
sort_indices = pc.sort_indices(
    employee_table,
    sort_keys=[("salary", "descending")]
)
sorted_table = employee_table.take(sort_indices)

print("=== Bonus 6: Employees sorted by salary (descending) ===")
print(sorted_table)