# -*- coding: utf-8 -*-
"""Python Parquet Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kzVN3gwUnYMsQq2iOG_YX7t602OXqVgQ
"""

Download Dataset :https://www.kaggle.com/datasets/prince7489/employee-salary-dataset?resource=download

import pandas as pd

# ==========================================
# Task 1: Create a DataFrame
# Dataset derived from Kaggle's Employee Salary Dataset
# Link: https://www.kaggle.com/datasets/prince7489/employee-salary-dataset
# ==========================================
data = {
    "employee_id": [1, 2, 3, 4, 5, 6, 7],
    "name": ["Asha Sharma", "Rahul Verma", "Neha Kapoor", "Vikram Patel", "Priya Nair", "Amit Singh", "Sneha Rao"],
    "department": ["IT", "HR", "IT", "Finance", "HR", "IT", "Finance"],
    "salary": [60000, 45000, 70000, 55000, 48000, 82000, 52000]
}

employees_df = pd.DataFrame(data)
print("--- Initial DataFrame (Task 1) ---")
print(employees_df)
print("\n" + "="*50 + "\n")

# ==========================================
# Task 2: Save as Parquet
# Save without the DataFrame index
# ==========================================
file_path = "employees.parquet"
employees_df.to_parquet(file_path, index=False, engine="pyarrow")
print(f"[Task 2] DataFrame successfully saved to '{file_path}' (without index).")
print("\n" + "="*50 + "\n")

# ==========================================
# Task 3: Read the Parquet File
# Read the Parquet file into a new DataFrame and display contents
# ==========================================
loaded_df = pd.read_parquet(file_path, engine="pyarrow")
print("--- Loaded DataFrame from Parquet (Task 3) ---")
print(loaded_df)
print("\n" + "="*50 + "\n")

# ==========================================
# Task 4: Perform Basic Analysis
# ==========================================
print("--- Basic Analysis Results (Task 4) ---")

# 1. Employees with salary > 50000
high_salary_df = loaded_df[loaded_df["salary"] > 50000]
print("\n1. Employees with Salary > 50,000:")
print(high_salary_df)

# 2. Calculate average salary
avg_salary = loaded_df["salary"].mean()
print(f"\n2. Average Employee Salary: ${avg_salary:,.2f}")

# 3. Employee count per department
dept_counts = loaded_df["department"].value_counts()
print("\n3. Number of Employees per Department:")
print(dept_counts)
print("\n" + "="*50 + "\n")

# ==========================================
# Task 5: Save Filtered Data
# Save employees with salary > 50000 into high_salary_employees.parquet
# ==========================================
filtered_file_path = "high_salary_employees.parquet"
high_salary_df.to_parquet(filtered_file_path, index=False, engine="pyarrow")
print(f"[Task 5] High salary employees saved to '{filtered_file_path}'.")
print("\n" + "="*50 + "\n")

# ==========================================
# Bonus Task: Read Selected Columns Only
# Efficiently read only 'name' and 'salary' using the `columns` parameter
# ==========================================
selected_cols_df = pd.read_parquet(file_path, columns=["name", "salary"], engine="pyarrow")
print("--- Selected Columns ('name' and 'salary') (Bonus Task) ---")
print(selected_cols_df)