# -*- coding: utf-8 -*-
"""Apache Arrow Assignment Using Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pz7Vt_oouP97WFZ6C1xLNS7vGDhUwzby
"""

Download Dataset :https://www.kaggle.com/datasets/smayanj/employee-records-dataset

import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.ipc as ipc
import pyarrow.parquet as pq

# ==========================================
# Task 1: Create an Arrow Table
# Kaggle Dataset Reference:
# https://www.kaggle.com/datasets/smayanj/employee-records-dataset
# ==========================================
print("--- Task 1: Create Arrow Table ---")
data = {
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": ["Asha", "Rahul", "Neha", "Vikram", "Priya", "Arjun"],
    "department": ["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "salary": [60000, 45000, 70000, 55000, 48000, 65000],
    "city": ["Delhi", "Mumbai", "Bengaluru", "Delhi", "Mumbai", "Chennai"],
}

employee_table = pa.table(data)
print(employee_table)

# ==========================================
# Task 2: Display the Schema
# ==========================================
print("\n--- Task 2: Display Schema ---")
print(employee_table.schema)

# Answers to Task 2 Questions:
# 1. Data type of 'employee_id': int64
# 2. Data type of 'name': string
# 3. Data type of 'salary': int64

# ==========================================
# Task 3: Inspect the Table
# ==========================================
print("\n--- Task 3: Inspect Table ---")
print("Rows:", employee_table.num_rows)
print("Columns:", employee_table.num_columns)
print("Column names:", employee_table.column_names)

print("\nName Column:")
print(employee_table.column("name"))

print("\nFirst Three Rows:")
print(employee_table.slice(0, 3))

# ==========================================
# Task 4: Select Specific Columns
# ==========================================
print("\n--- Task 4: Select Columns ---")
selected_table = employee_table.select(["name", "department", "salary"])
print(selected_table)

# ==========================================
# Task 5: Filter Records (Salary > 50000)
# ==========================================
print("\n--- Task 5: Salary > 50000 ---")
salary_filter = pc.greater(employee_table["salary"], 50000)
high_salary_table = employee_table.filter(salary_filter)
print(high_salary_table)

# ==========================================
# Task 6: Filter by Department (IT)
# ==========================================
print("\n--- Task 6: IT Department Employees ---")
department_filter = pc.equal(employee_table["department"], "IT")
it_employees = employee_table.filter(department_filter)
print(it_employees)

# ==========================================
# Task 7: Perform Calculations
# ==========================================
print("\n--- Task 7: Perform Calculations ---")
salary_column = employee_table["salary"]
print("Average salary:", pc.mean(salary_column).as_py())
print("Maximum salary:", pc.max(salary_column).as_py())
print("Minimum salary:", pc.min(salary_column).as_py())
print("Total salary:", pc.sum(salary_column).as_py())

# ==========================================
# Task 8: Add a New Column (Bonus)
# ==========================================
print("\n--- Task 8: Add Bonus Column ---")
bonus_column = pc.multiply(employee_table["salary"], 0.10)
employee_table = employee_table.append_column("bonus", bonus_column)
print(employee_table)

# ==========================================
# Task 9: Convert Arrow to Pandas
# ==========================================
print("\n--- Task 9: Convert Arrow to Pandas ---")
employee_df = employee_table.to_pandas()
print(employee_df)

# ==========================================
# Task 10: Convert Pandas to Arrow
# ==========================================
print("\n--- Task 10: Convert Pandas to Arrow ---")
new_arrow_table = pa.Table.from_pandas(employee_df, preserve_index=False)
print(new_arrow_table)

# ==========================================
# Task 11: Save as a Parquet File
# ==========================================
print("\n--- Task 11: Save to Parquet ---")
pq.write_table(employee_table, "employees.parquet")
print("Parquet file created successfully.")

# ==========================================
# Task 12: Read the Parquet File
# ==========================================
print("\n--- Task 12: Read Parquet File ---")
loaded_table = pq.read_table("employees.parquet")
print(loaded_table)

# ==========================================
# Task 13: Save as an Arrow IPC File
# ==========================================
print("\n--- Task 13: Save to Arrow IPC File ---")
with ipc.new_file("employees.arrow", employee_table.schema) as writer:
    writer.write_table(employee_table)
print("Arrow IPC file created successfully.")

# ==========================================
# Task 14: Read the Arrow IPC File
# ==========================================
print("\n--- Task 14: Read Arrow IPC File ---")
with ipc.open_file("employees.arrow") as reader:
    ipc_table = reader.read_all()
print(ipc_table)

# ==========================================
# Bonus Tasks
# ==========================================
print("\n--- Bonus Tasks ---")

# Bonus 1: Display employees who work in Delhi
delhi_filter = pc.equal(employee_table["city"], "Delhi")
delhi_employees = employee_table.filter(delhi_filter)
print("\nBonus 1 - Delhi Employees:")
print(delhi_employees)

# Bonus 2: Display employees with salaries between 50000 and 65000
salary_range_filter = pc.and_(
    pc.greater_equal(employee_table["salary"], 50000),
    pc.less_equal(employee_table["salary"], 65000),
)
mid_salary_employees = employee_table.filter(salary_range_filter)
print("\nBonus 2 - Salary between 50000 and 65000:")
print(mid_salary_employees)

# Bonus 3: Add a column named annual_salary by multiplying salary by 12
annual_salary_column = pc.multiply(employee_table["salary"], 12)
employee_table = employee_table.append_column(
    "annual_salary", annual_salary_column
)
print("\nBonus 3 - Added Annual Salary Column:")
print(employee_table)

# Bonus 4: Save only IT employees to it_employees.parquet
pq.write_table(it_employees, "it_employees.parquet")
print("\nBonus 4 - IT employees saved to 'it_employees.parquet'.")

# Bonus 5: Read only name and salary columns from Parquet file
selected_columns = pq.read_table(
    "employees.parquet", columns=["name", "salary"]
)
print("\nBonus 5 - Selected columns from Parquet:")
print(selected_columns)

# Bonus 6: Sort employees by salary from highest to lowest
# Using pc.sort_indices with a list of (column, order) tuples for the table
sort_indices = pc.sort_indices(employee_table, sort_keys=[("salary", "descending")])
sorted_table = employee_table.take(sort_indices)
print("\nBonus 6 - Sorted Employees by Salary (Descending):")
print(sorted_table)