# -*- coding: utf-8 -*-
"""DuckDB Assignment Using Parquet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iDUxqw9ZaAyfXJ1T1LXBZWvFP3nvquwa

Download Dataset :https://www.kaggle.com/datasets/prince7489/employee-salary-dataset
"""

import duckdb
import pandas as pd

# ==============================================================================
# Task 1: Create the Parquet File
# ==============================================================================
print("--- Task 1: Creating Parquet File ---")
data = {
    "employee_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "name": [
        "Asha",
        "Rahul",
        "Neha",
        "Vikram",
        "Priya",
        "Arjun",
        "Meera",
        "Karan",
        "Ananya",
        "Rohan",
    ],
    "department": [
        "IT",
        "HR",
        "IT",
        "Finance",
        "HR",
        "Finance",
        "IT",
        "Sales",
        "IT",
        "Sales",
    ],
    "salary": [
        60000,
        45000,
        70000,
        55000,
        48000,
        65000,
        75000,
        50000,
        82000,
        52000,
    ],
    "city": [
        "Delhi",
        "Mumbai",
        "Bengaluru",
        "Delhi",
        "Mumbai",
        "Chennai",
        "Bengaluru",
        "Delhi",
        "Bengaluru",
        "Mumbai",
    ],
}

df = pd.DataFrame(data)
df.to_parquet("employees.parquet", index=False)
print("Parquet file 'employees.parquet' created successfully.\n")


# ==============================================================================
# Task 2: Read Parquet Using DuckDB
# ==============================================================================
print("--- Task 2: Read Parquet File ---")
all_employees = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
""").df()
print(all_employees)
print("\n")


# ==============================================================================
# Task 3: Filter Employee Records
# ==============================================================================
print("--- Task 3: Filter Employee Records ---")

# 1. Salary > 50000
high_salary = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    WHERE salary > 50000
""").df()
print("1. Salary > 50000:\n", high_salary)

# 2. IT Department
it_dept = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    WHERE department = 'IT'
""").df()
print("\n2. IT Department:\n", it_dept)

# 3. Work in Delhi
delhi_employees = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    WHERE city = 'Delhi'
""").df()
print("\n3. Employees in Delhi:\n", delhi_employees)

# 4. IT Department with Salary > 65000
it_high_salary = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    WHERE department = 'IT' AND salary > 65000
""").df()
print("\n4. IT Department & Salary > 65000:\n", it_high_salary)
print("\n")


# ==============================================================================
# Task 4: Select Specific Columns & Sort
# ==============================================================================
print("--- Task 4: Select Specific Columns & Sort ---")
sorted_employees = duckdb.sql("""
    SELECT name, department, salary
    FROM read_parquet('employees.parquet')
    ORDER BY salary DESC
""").df()
print(sorted_employees)
print("\n")


# ==============================================================================
# Task 5: Perform Aggregations
# ==============================================================================
print("--- Task 5: Aggregate Calculations ---")
aggregations = duckdb.sql("""
    SELECT
        COUNT(*) AS total_employees,
        AVG(salary) AS average_salary,
        MAX(salary) AS maximum_salary,
        MIN(salary) AS minimum_salary,
        SUM(salary) AS total_salary
    FROM read_parquet('employees.parquet')
""").df()
print(aggregations)
print("\n")


# ==============================================================================
# Task 6: Group Data by Department
# ==============================================================================
print("--- Task 6: Group Data by Department ---")
dept_summary = duckdb.sql("""
    SELECT
        department,
        COUNT(*) AS employee_count,
        AVG(salary) AS average_salary,
        MAX(salary) AS highest_salary,
        SUM(salary) AS total_salary
    FROM read_parquet('employees.parquet')
    GROUP BY department
    ORDER BY average_salary DESC
""").df()
print(dept_summary)
print("\n")


# ==============================================================================
# Task 7: Create a DuckDB Table & Database File
# ==============================================================================
print("--- Task 7: Persistent DuckDB Database Table ---")
connection = duckdb.connect("company.duckdb")

connection.execute("""
    CREATE OR REPLACE TABLE employees AS
    SELECT *
    FROM read_parquet('employees.parquet')
""")

table_data = connection.execute("SELECT * FROM employees").df()
print("Data read from 'company.duckdb':\n", table_data)
connection.close()
print("\n")


# ==============================================================================
# Task 8: Export Query Results to Parquet
# ==============================================================================
print("--- Task 8: Export Filtered Data to Parquet ---")
duckdb.sql("""
    COPY (
        SELECT *
        FROM read_parquet('employees.parquet')
        WHERE salary > 50000
    )
    TO 'high_salary_employees.parquet'
    (FORMAT PARQUET)
""")
print(
    "Filtered data successfully saved to 'high_salary_employees.parquet'.\n"
)


# ==============================================================================
# Task 9: Verify the Exported File
# ==============================================================================
print("--- Task 9: Verify Exported Parquet File ---")
exported_result = duckdb.sql("""
    SELECT *
    FROM read_parquet('high_salary_employees.parquet')
""").df()
print(exported_result)
print("\n")


# ==============================================================================
# Bonus Tasks
# ==============================================================================
print("--- Bonus Tasks ---")

# Bonus 1: Employee with the second-highest salary
second_highest = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    ORDER BY salary DESC
    LIMIT 1 OFFSET 1
""").df()
print("1. Second-highest salary employee:\n", second_highest)

# Bonus 2: Top three highest-paid employees
top_three = duckdb.sql("""
    SELECT *
    FROM read_parquet('employees.parquet')
    ORDER BY salary DESC
    LIMIT 3
""").df()
print("\n2. Top 3 highest-paid employees:\n", top_three)

# Bonus 3: Average salary for each city
city_avg_salary = duckdb.sql("""
    SELECT city, AVG(salary) AS average_salary
    FROM read_parquet('employees.parquet')
    GROUP BY city
    ORDER BY average_salary DESC
""").df()
print("\n3. Average salary by city:\n", city_avg_salary)

# Bonus 4: Departments with average salary > 55000
dept_above_55k = duckdb.sql("""
    SELECT department, AVG(salary) AS average_salary
    FROM read_parquet('employees.parquet')
    GROUP BY department
    HAVING AVG(salary) > 55000
""").df()
print("\n4. Departments with average salary > 55000:\n", dept_above_55k)

# Bonus 5: Calculated column salary_category
salary_categories = duckdb.sql("""
    SELECT
        name,
        salary,
        CASE
            WHEN salary >= 65000 THEN 'High'
            WHEN salary >= 50000 THEN 'Medium'
            ELSE 'Low'
        END AS salary_category
    FROM read_parquet('employees.parquet')
""").df()
print("\n5. Salary Categories:\n", salary_categories)