# -*- coding: utf-8 -*-
"""Customer Segmentation with Actionable Business Insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-hh5_14tPeMbQ7HerV9AMIJOJ8l8bRv3

Download dataset https://www.kaggle.com/datasets/palvinder2006/customer-dataset
"""

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression, Ridge, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import (
    silhouette_score, mean_absolute_error, mean_squared_error, r2_score,
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,
    confusion_matrix, classification_report
)

warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid', palette='muted')

# =====================================================================
# STEP 1: DATA LOADING & SYNTHETIC FALLBACK GENERATOR
# =====================================================================
DATA_FILE = 'customer_data.csv'

def load_or_generate_data(filename=DATA_FILE, n_samples=1000):
    if os.path.exists(filename):
        print(f"Loading dataset from '{filename}'...")
        df = pd.read_csv(filename)
    else:
        print(f"File '{filename}' not found. Generating synthetic dataset matching project schema...")
        np.random.seed(42)

        customer_ids = [f"CUST_{1000 + i}" for i in range(n_samples)]
        age = np.random.randint(18, 70, size=n_samples)
        gender = np.random.choice(['Male', 'Female'], size=n_samples)
        annual_income = np.round(np.random.normal(65000, 20000, n_samples).clip(20000, 150000), 2)

        purchase_freq = np.random.poisson(lam=12, size=n_samples).clip(1, 50)
        avg_order_val = np.round(np.random.exponential(scale=80, size=n_samples) + 20, 2)
        total_spending = np.round(purchase_freq * avg_order_val, 2)

        days_since_last = np.random.randint(1, 180, size=n_samples)
        website_visits = np.random.randint(2, 60, size=n_samples)
        discount_usage = np.round(np.random.uniform(0.0, 0.6, size=n_samples), 2)
        customer_rating = np.round(np.random.uniform(1.0, 5.0, size=n_samples), 1)

        categories = ['Electronics', 'Apparel', 'Home & Kitchen', 'Beauty', 'Books']
        product_cat = np.random.choice(categories, size=n_samples)

        # Likelihood driven logically by recency, frequency, and spending
        logit = (0.05 * purchase_freq) - (0.02 * days_since_last) + (0.0005 * total_spending) + (0.5 * customer_rating) - 2.0
        prob = 1 / (1 + np.exp(-logit))
        purchase_likelihood = (prob > 0.5).astype(int)

        df = pd.DataFrame({
            'CustomerID': customer_ids,
            'Age': age,
            'Gender': gender,
            'AnnualIncome': annual_income,
            'TotalSpending': total_spending,
            'PurchaseFrequency': purchase_freq,
            'AverageOrderValue': avg_order_val,
            'DaysSinceLastPurchase': days_since_last,
            'WebsiteVisits': website_visits,
            'DiscountUsage': discount_usage,
            'CustomerRating': customer_rating,
            'ProductCategory': product_cat,
            'PurchaseLikelihood': purchase_likelihood
        })
        df.to_csv(filename, index=False)
        print(f"Synthetic dataset saved to '{filename}'.")
    return df

df = load_or_generate_data()

# =====================================================================
# STEP 2: EXPLORATORY DATA ANALYSIS (EDA) & PREPROCESSING
# =====================================================================
print("\n--- DATA OVERVIEW ---")
print(df.info())
print("\n--- SUMMARY STATISTICS ---")
print(df.describe().T)

# Missing values check
missing_vals = df.isnull().sum().sum()
print(f"\nTotal Missing Values: {missing_vals}")
if missing_vals > 0:
    df.fillna(df.median(numeric_only=True), inplace=True)

# Outlier treatment via IQR capping on key numerical columns
num_cols = ['AnnualIncome', 'TotalSpending', 'PurchaseFrequency', 'AverageOrderValue', 'DaysSinceLastPurchase']
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df[col] = np.clip(df[col], lower_bound, upper_bound)

# Visualizing distributions
plt.figure(figsize=(14, 5))
plt.subplot(1, 2, 1)
sns.histplot(df['TotalSpending'], kde=True, color='teal')
plt.title('Customer Total Spending Distribution')

plt.subplot(1, 2, 2)
sns.scatterplot(data=df, x='DaysSinceLastPurchase', y='PurchaseFrequency', hue='PurchaseLikelihood', palette='Set1', alpha=0.7)
plt.title('Recency vs. Frequency by Purchase Likelihood')
plt.tight_layout()
plt.show()

# Encoding categorical attributes
df_proc = df.copy()
le = LabelEncoder()
df_proc['Gender_Encoded'] = le.fit_transform(df_proc['Gender'])
df_proc = pd.get_dummies(df_proc, columns=['ProductCategory'], drop_first=True)

# =====================================================================
# STEP 3: K-MEANS CLUSTERING & SEGMENT PROFILING
# =====================================================================
clustering_features = ['DaysSinceLastPurchase', 'PurchaseFrequency', 'TotalSpending', 'AverageOrderValue', 'DiscountUsage', 'CustomerRating']
X_cluster = df_proc[clustering_features]

scaler = StandardScaler()
X_cluster_scaled = scaler.fit_transform(X_cluster)

# Elbow Method and Silhouette Score calculation
k_range = range(2, 9)
inertias = []
silhouette_scores = []

for k in k_range:
    km = KMeans(n_clusters=k, init='k-means++', n_init=10, max_iter=300, random_state=42)
    km.fit(X_cluster_scaled)
    inertias.append(km.inertia_)
    silhouette_scores.append(silhouette_score(X_cluster_scaled, km.labels_))

# Plotting Elbow and Silhouette curves
fig, ax1 = plt.subplots(figsize=(12, 5))
ax1.set_xlabel('Number of Clusters (k)')
ax1.set_ylabel('Inertia (Elbow)', color='tab:blue')
ax1.plot(k_range, inertias, marker='o', color='tab:blue', linewidth=2, label='Inertia')
ax1.tick_params(axis='y', labelcolor='tab:blue')

ax2 = ax1.twinx()
ax2.set_ylabel('Silhouette Score', color='tab:red')
ax2.plot(k_range, silhouette_scores, marker='s', color='tab:red', linewidth=2, linestyle='--', label='Silhouette')
ax2.tick_params(axis='y', labelcolor='tab:red')

plt.title('Optimal k Selection: Elbow Method & Silhouette Scores')
fig.tight_layout()
plt.show()

# Selecting final clusters (k = 5)
optimal_k = 5
final_kmeans = KMeans(n_clusters=optimal_k, init='k-means++', n_init=15, max_iter=300, random_state=42)
df['Cluster'] = final_kmeans.fit_predict(X_cluster_scaled)
df_proc['Cluster'] = df['Cluster']

# PCA for 2D Visualization
pca = PCA(n_components=2, random_state=42)
pca_coords = pca.fit_transform(X_cluster_scaled)
df['PCA1'] = pca_coords[:, 0]
df['PCA2'] = pca_coords[:, 1]

plt.figure(figsize=(9, 6))
sns.scatterplot(data=df, x='PCA1', y='PCA2', hue='Cluster', palette='tab10', style='Cluster', s=70, alpha=0.85)
plt.title('2D PCA Projection of Customer Segments')
plt.xlabel(f'PCA Component 1 ({pca.explained_variance_ratio_[0]*100:.1f}%)')
plt.ylabel(f'PCA Component 2 ({pca.explained_variance_ratio_[1]*100:.1f}%)')
plt.legend(title='Cluster')
plt.show()

# Segment Profiling
cluster_profile = df.groupby('Cluster').agg({
    'CustomerID': 'count',
    'TotalSpending': 'mean',
    'PurchaseFrequency': 'mean',
    'DaysSinceLastPurchase': 'mean',
    'AverageOrderValue': 'mean',
    'DiscountUsage': 'mean',
    'CustomerRating': 'mean'
}).rename(columns={'CustomerID': 'CustomerCount'}).reset_index()

cluster_profile['RevenueShare (%)'] = np.round(
    (cluster_profile['TotalSpending'] * cluster_profile['CustomerCount']) /
    (df['TotalSpending'].sum()) * 100, 2
)

# Assign Business Names based on cluster properties
def map_segment_name(row):
    if row['TotalSpending'] > df['TotalSpending'].quantile(0.70) and row['DaysSinceLastPurchase'] < df['DaysSinceLastPurchase'].quantile(0.40):
        return 'High-Value Loyal'
    elif row['DaysSinceLastPurchase'] > df['DaysSinceLastPurchase'].quantile(0.65) and row['TotalSpending'] > df['TotalSpending'].quantile(0.40):
        return 'At-Risk'
    elif row['DiscountUsage'] > df['DiscountUsage'].quantile(0.60):
        return 'Discount-Driven'
    elif row['PurchaseFrequency'] < df['PurchaseFrequency'].quantile(0.35) and row['TotalSpending'] < df['TotalSpending'].quantile(0.35):
        return 'Low-Engagement'
    else:
        return 'New & Promising'

# Apply fallback dynamic map to guarantee unique clean segment labels
cluster_name_map = {}
for idx, row in cluster_profile.iterrows():
    cluster_name_map[row['Cluster']] = f"Segment {int(row['Cluster'])}: " + map_segment_name(row)

df['Segment_Name'] = df['Cluster'].map(cluster_name_map)
cluster_profile['Segment_Name'] = cluster_profile['Cluster'].map(cluster_name_map)

print("\n--- CLUSTER PROFILES & REVENUE CONTRIBUTION ---")
print(cluster_profile.to_string(index=False))

# =====================================================================
# STEP 4: REGRESSION MODELING (PREDICTING TOTAL SPENDING)
# =====================================================================
reg_features = ['Age', 'AnnualIncome', 'PurchaseFrequency', 'AverageOrderValue', 'DaysSinceLastPurchase', 'WebsiteVisits', 'DiscountUsage', 'CustomerRating', 'Cluster']
X_reg = pd.get_dummies(df_proc[reg_features], columns=['Cluster'], drop_first=True)
y_reg = df_proc['TotalSpending']

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)

scaler_r = StandardScaler()
X_train_r_scaled = scaler_r.fit_transform(X_train_r)
X_test_r_scaled = scaler_r.transform(X_test_r)

# Baseline: Linear Regression
lr_base = LinearRegression()
lr_base.fit(X_train_r_scaled, y_train_r)
y_pred_lr = lr_base.predict(X_test_r_scaled)

# Tuned Model: Ridge Regression with GridSearchCV
ridge_params = {'alpha': [0.01, 0.1, 1.0, 10.0, 100.0, 200.0]}
ridge_grid = GridSearchCV(Ridge(random_state=42), ridge_params, cv=5, scoring='neg_root_mean_squared_error')
ridge_grid.fit(X_train_r_scaled, y_train_r)
best_ridge = ridge_grid.best_estimator_
y_pred_ridge = best_ridge.predict(X_test_r_scaled)

def evaluate_regression(y_true, y_pred, name="Model"):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    return {'Model': name, 'MAE': round(mae, 2), 'MSE': round(mse, 2), 'RMSE': round(rmse, 2), 'R2': round(r2, 4)}

reg_results = [
    evaluate_regression(y_test_r, y_pred_lr, "Linear Regression (Baseline)"),
    evaluate_regression(y_test_r, y_pred_ridge, f"Ridge Regression (Tuned, alpha={best_ridge.alpha})")
]
print("\n--- REGRESSION MODEL PERFORMANCE ---")
print(pd.DataFrame(reg_results).to_string(index=False))

# Scatter plot: Actual vs Predicted
plt.figure(figsize=(7, 5))
plt.scatter(y_test_r, y_pred_ridge, alpha=0.6, color='indigo')
plt.plot([y_test_r.min(), y_test_r.max()], [y_test_r.min(), y_test_r.max()], 'r--', lw=2)
plt.title('Ridge Regression: Actual vs. Predicted Total Spending')
plt.xlabel('Actual Spending ($)')
plt.ylabel('Predicted Spending ($)')
plt.tight_layout()
plt.show()

# =====================================================================
# STEP 5: CLASSIFICATION MODELING (PURCHASE LIKELIHOOD)
# =====================================================================
clf_features = ['DaysSinceLastPurchase', 'PurchaseFrequency', 'TotalSpending', 'CustomerRating', 'WebsiteVisits', 'DiscountUsage', 'Cluster']
X_clf = pd.get_dummies(df_proc[clf_features], columns=['Cluster'], drop_first=True)
y_clf = df_proc['PurchaseLikelihood']

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_clf, y_clf, test_size=0.2, random_state=42, stratify=y_clf)

scaler_c = StandardScaler()
X_train_c_scaled = scaler_c.fit_transform(X_train_c)
X_test_c_scaled = scaler_c.transform(X_test_c)

# Baseline: Logistic Regression
log_base = LogisticRegression(random_state=42)
log_base.fit(X_train_c_scaled, y_train_c)
y_pred_base = log_base.predict(X_test_c_scaled)
y_prob_base = log_base.predict_proba(X_test_c_scaled)[:, 1]

# Tuned: Logistic Regression via GridSearchCV
log_params = {
    'C': [0.01, 0.1, 1.0, 10.0],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear', 'saga'],
    'max_iter': [300]
}
log_grid = GridSearchCV(LogisticRegression(random_state=42), log_params, cv=5, scoring='f1')
log_grid.fit(X_train_c_scaled, y_train_c)
best_log = log_grid.best_estimator_
y_pred_tuned = best_log.predict(X_test_c_scaled)
y_prob_tuned = best_log.predict_proba(X_test_c_scaled)[:, 1]

def evaluate_classification(y_true, y_pred, y_prob, name="Model"):
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    roc = roc_auc_score(y_true, y_prob)
    return {'Model': name, 'Accuracy': round(acc, 4), 'Precision': round(prec, 4), 'Recall': round(rec, 4), 'F1-Score': round(f1, 4), 'ROC-AUC': round(roc, 4)}

clf_results = [
    evaluate_classification(y_test_c, y_pred_base, y_prob_base, "Logistic Regression (Baseline)"),
    evaluate_classification(y_test_c, y_pred_tuned, y_prob_tuned, f"Logistic Regression (Tuned)")
]
print("\n--- CLASSIFICATION MODEL PERFORMANCE ---")
print(pd.DataFrame(clf_results).to_string(index=False))

# Confusion Matrix plot
cm = confusion_matrix(y_test_c, y_pred_tuned)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['No Purchase', 'Purchase'], yticklabels=['No Purchase', 'Purchase'])
plt.title('Confusion Matrix - Tuned Logistic Regression')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.tight_layout()
plt.show()

# Export segmented customer dataframe
df.to_csv('segmented_customers_output.csv', index=False)
print("\nProcess completed successfully! Output saved to 'segmented_customers_output.csv'.")