# -*- coding: utf-8 -*-
"""parquet_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nlzsJ6SA1TbCqpXHJDljBzOIaoWblRt
"""

import pandas as pd

data = {
    "employee_id": [1, 2, 3, 4, 5],
    "name": ["Asha", "Rahul", "Neha", "Vikram", "Priya"],
    "department": ["IT", "HR", "IT", "Finance", "HR"],
    "salary": [60000, 45000, 70000, 55000, 48000]
}

# Task 1: Create the DataFrame
employees_df = pd.DataFrame(data)

print("Original DataFrame:")
print(employees_df)

# Task 2: Save the DataFrame as a Parquet file
employees_df.to_parquet('employees.parquet', index=False)
print("\nDataFrame saved to employees.parquet")

# Task 3: Read the Parquet file
read_employees_df = pd.read_parquet('employees.parquet')
print("\nDataFrame read from employees.parquet:")
print(read_employees_df)

# Task 4: Perform the requested analysis
# 1. Display employees with a salary greater than 50000
high_salary_employees_df = read_employees_df[read_employees_df['salary'] > 50000]
print("\nEmployees with salary greater than 50000:")
print(high_salary_employees_df)

# 2. Calculate the average salary
average_salary = read_employees_df['salary'].mean()
print(f"\nAverage Salary: {average_salary:.2f}")

# 3. Display the number of employees in each department
employees_by_department = read_employees_df['department'].value_counts()
print("\nNumber of employees in each department:")
print(employees_by_department)

# Task 5: Save the filtered data
high_salary_employees_df.to_parquet('high_salary_employees.parquet', index=False)
print("\nHigh salary employees saved to high_salary_employees.parquet")

# Bonus Task: Read only the `name` and `salary` columns
name_salary_df = pd.read_parquet('employees.parquet', columns=['name', 'salary'])
print("\nDataFrame with only 'name' and 'salary' columns:")
print(name_salary_df)