name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */6 * * *"  # runs every 6 hours
  workflow_dispatch:        # lets you trigger it manually too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the app
        run: curl -sS https://castingqualityinspection-7rqvvunr6vhbvtmofcgebm.streamlit.app/ > /dev/null